# permissions for end users to view externals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: external-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fabric
    app.kubernetes.io/part-of: fabric
    app.kubernetes.io/managed-by: kustomize
  name: external-viewer-role
rules:
- apiGroups:
  - vpc.githedgehog.com
  resources:
  - externals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpc.githedgehog.com
  resources:
  - externals/status
  verbs:
  - get
