###
### rack-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Rack
metadata:
  name: rack-1
spec:
---
###
### switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: b7e0848d-15f9-5f46-ac21-1710a7b792f0
    fabric.githedgehog.com/rack: rack-1
  name: switch-1
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "1"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: 81c9671f-0b80-5a45-b946-686de0b9aaa9
    fabric.githedgehog.com/rack: rack-1
  name: switch-2
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "2"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### control-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: 1e9df880-96d7-5806-8413-0d1d4fd19df2
    fabric.githedgehog.com/rack: rack-1
  name: control-1
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "3"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
  type: control
---
###
### compute-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: cf8e1bf2-ebc3-552a-a149-4112ce95fc2c
    fabric.githedgehog.com/rack: rack-1
  name: compute-1
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "4"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### compute-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: 1fee30cf-7a35-5ad8-9e5d-2b6ec0e56d0c
    fabric.githedgehog.com/rack: rack-1
  name: compute-2
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "5"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### compute-3
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: b2b2ddbd-9197-5cc2-aeeb-b16d806ffe63
    fabric.githedgehog.com/rack: rack-1
  name: compute-3
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "6"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### compute-4
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/location: 88e6f03a-74b9-51af-a637-6fc6ef594694
    fabric.githedgehog.com/rack: rack-1
  name: compute-4
spec:
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "7"
  locationSig:
    sig: long-signature
    uuidSig: also-long-signature
---
###
### compute-1--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.connection.fabric.githedgehog.com/rack-1: "true"
    server.connection.fabric.githedgehog.com/compute-1: "true"
    switch.connection.fabric.githedgehog.com/switch-1: "true"
    switch.connection.fabric.githedgehog.com/switch-2: "true"
  name: compute-1--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: compute-1/nic0/port0
      switch:
        port: switch-1/Ethernet2
    - server:
        port: compute-1/nic0/port1
      switch:
        port: switch-2/Ethernet2
---
###
### compute-2--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.connection.fabric.githedgehog.com/rack-1: "true"
    server.connection.fabric.githedgehog.com/compute-2: "true"
    switch.connection.fabric.githedgehog.com/switch-1: "true"
    switch.connection.fabric.githedgehog.com/switch-2: "true"
  name: compute-2--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: compute-2/nic0/port0
      switch:
        port: switch-1/Ethernet3
    - server:
        port: compute-2/nic0/port1
      switch:
        port: switch-2/Ethernet3
---
###
### compute-3--unbundled--switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.connection.fabric.githedgehog.com/rack-1: "true"
    server.connection.fabric.githedgehog.com/compute-3: "true"
    switch.connection.fabric.githedgehog.com/switch-1: "true"
  name: compute-3--unbundled--switch-1
spec:
  unbundled:
    link:
      server:
        port: compute-3/nic0/port0
      switch:
        port: switch-1/Ethernet4
---
###
### compute-4--unbundled--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.connection.fabric.githedgehog.com/rack-1: "true"
    server.connection.fabric.githedgehog.com/compute-4: "true"
    switch.connection.fabric.githedgehog.com/switch-2: "true"
  name: compute-4--unbundled--switch-2
spec:
  unbundled:
    link:
      server:
        port: compute-4/nic0/port0
      switch:
        port: switch-2/Ethernet4
---
###
### control-1--mgmt--switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.connection.fabric.githedgehog.com/rack-1: "true"
    server.connection.fabric.githedgehog.com/control-1: "true"
    switch.connection.fabric.githedgehog.com/switch-1: "true"
  name: control-1--mgmt--switch-1
spec:
  management:
    link:
      server:
        port: control-1/eth1
      switch:
        ip: 192.168.42.11/24
        oniePortName: eth0
        port: switch-1/Management0
        vlan: 42
---
###
### control-1--mgmt--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.connection.fabric.githedgehog.com/rack-1: "true"
    server.connection.fabric.githedgehog.com/control-1: "true"
    switch.connection.fabric.githedgehog.com/switch-2: "true"
  name: control-1--mgmt--switch-2
spec:
  management:
    link:
      server:
        port: control-1/eth2
      switch:
        ip: 192.168.42.12/24
        oniePortName: eth0
        port: switch-2/Management0
        vlan: 42
---
###
### switch-1--mclag-domain--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    rack.connection.fabric.githedgehog.com/rack-1: "true"
    server.connection.fabric.githedgehog.com/switch-1: "true"
    switch.connection.fabric.githedgehog.com/switch-2: "true"
  name: switch-1--mclag-domain--switch-2
spec:
  mclagDomain:
    links:
    - switch1:
        port: switch-1/Ethernet0
      switch2:
        port: switch-2/Ethernet0
    - switch1:
        port: switch-1/Ethernet1
      switch2:
        port: switch-2/Ethernet1
