###
### rack-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Rack
metadata:
  name: rack-1
spec:
---
###
### switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: b7e0848d-15f9-5f46-ac21-1710a7b792f0
    fabric.githedgehog.com/rack: rack-1
  name: switch-1
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "1"
  locationSig:
    sig: <undefined>
    uuidSig: <undefined>
  portGroupSpeeds:
    "1": SPEED_10GB
    "12": SPEED_10GB
---
###
### switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Switch
metadata:
  labels:
    fabric.githedgehog.com/location: 81c9671f-0b80-5a45-b946-686de0b9aaa9
    fabric.githedgehog.com/rack: rack-1
  name: switch-2
spec:
  lldp: {}
  location:
    aisle: "1"
    location: LOC
    rack: "1"
    row: "1"
    slot: "2"
  locationSig:
    sig: <undefined>
    uuidSig: <undefined>
  portGroupSpeeds:
    "1": SPEED_10GB
    "12": SPEED_10GB
---
###
### control-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
    fabric.githedgehog.com/server-type: control
  name: control-1
spec:
  type: control
---
###
### server-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
    fabric.githedgehog.com/server-type: ""
  name: server-1
spec: {}
---
###
### server-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
    fabric.githedgehog.com/server-type: ""
  name: server-2
spec: {}
---
###
### server-3
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Server
metadata:
  labels:
    fabric.githedgehog.com/rack: rack-1
    fabric.githedgehog.com/server-type: ""
  name: server-3
spec: {}
---
###
### control-1--mgmt--switch-1
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: management
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
  name: control-1--mgmt--switch-1
spec:
  management:
    link:
      server:
        ip: 192.168.101.1/31
        port: control-1/eno2
      switch:
        ip: 192.168.101.0/31
        oniePortName: eth0
        port: switch-1/Management0
---
###
### control-1--mgmt--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: management
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/control-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: control-1--mgmt--switch-2
spec:
  management:
    link:
      server:
        ip: 192.168.102.1/31
        port: control-1/eno3
      switch:
        ip: 192.168.102.0/31
        oniePortName: eth0
        port: switch-2/Management0
---
###
### server-1--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/server-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-1--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-1/enp7s0
      switch:
        port: switch-1/Ethernet47
    - server:
        port: server-1/enp8s0
      switch:
        port: switch-2/Ethernet46
---
###
### server-2--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/server-2: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-2--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-2/enp7s0
      switch:
        port: switch-1/Ethernet46
    - server:
        port: server-2/enp8s0
      switch:
        port: switch-2/Ethernet47
---
###
### server-3--mclag--switch-1--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag
    rack.fabric.githedgehog.com/rack-1: "true"
    server.fabric.githedgehog.com/server-3: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: server-3--mclag--switch-1--switch-2
spec:
  mclag:
    links:
    - server:
        port: server-3/ens3f0
      switch:
        port: switch-1/Ethernet6
    - server:
        port: server-3/ens3f1
      switch:
        port: switch-2/Ethernet6
---
###
### switch-1--mclag-domain--switch-2
###
apiVersion: wiring.githedgehog.com/v1alpha2
kind: Connection
metadata:
  labels:
    fabric.githedgehog.com/connection-type: mclag-domain
    rack.fabric.githedgehog.com/rack-1: "true"
    switch.fabric.githedgehog.com/switch-1: "true"
    switch.fabric.githedgehog.com/switch-2: "true"
  name: switch-1--mclag-domain--switch-2
spec:
  mclagDomain:
    peerLinks:
    - switch1:
        port: switch-1/Ethernet48
      switch2:
        port: switch-2/Ethernet48
    - switch1:
        port: switch-1/Ethernet56
      switch2:
        port: switch-2/Ethernet56
    sessionLinks:
    - switch1:
        port: switch-1/Ethernet64
      switch2:
        port: switch-2/Ethernet64
    - switch1:
        port: switch-1/Ethernet68
      switch2:
        port: switch-2/Ethernet68
